export const MOVIES_TYPE = {
  NOW_PLAYING: "NOW_PLAYING",
  DETAIL: "DETAIL",
  DISCOVER: "DISCOVER",
  KEYWORDS: "KEYWORDS",
  VIDEOS: "VIDEOS",
  CREDITS: "CREDITS",
  SEARCH: "SEARCH",
  POPULAR: "POPULAR",
  UPCOMING: "UPCOMING",
  PEOPLES: "PEOPLES",
  PEOPLE_DETAIL: "PEOPLE_DETAIL",
};
